version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: arboris_postgis
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: arboris
    ports:
      - "5433:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis_data:
